import Head from "next/head";
import {VscGithubInverted,} from "react-icons/vsc";
import {SiLinkedin,} from "react-icons/si";
import {BsFillPinMapFill} from "react-icons/bs";
import {GrMail,} from "react-icons/gr";
import {IoMdSchool,} from "react-icons/io";
import { TfiLightBulb } from "react-icons/tfi";
import { RiGithubLine } from "react-icons/ri";
import { AiOutlineToTop } from "react-icons/ai";
import { MdOutlineFeaturedPlayList } from "react-icons/md";
import { ImAmazon } from "react-icons/im";
import { VscWarning } from "react-icons/vsc";
import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(true);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Daniel Khan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <header aria-label="Site Header"  className="bg-stone-100 px-8 dark:bg-zinc-800 md:px-10 lg:px-40">
        <div className="mx-auto flex max-w-screen-xl items-center justify-between px-4">
          <nav aria-label="Site Nav" className="hidden items-center justify-center gap-8 py-4 text-sm font-medium lg:flex lg:w-0 lg:flex-1">
          <a className="flex-shrink-0 pr-8 pl-4 bg-clip-text bg-gradient-to-r from-red-900 to-slate-900 dark:to-slate-100 tracking-widest font-black text-transparent" href="#">Daniel Khan</a>
            <a className="text-gray-900 dark:text-white" href="#About">About</a>
            <a className="text-gray-900 dark:text-white" href="#Experience">Experience</a>
            <a className="text-gray-900 dark:text-white" href="#Projects">Projects</a>
            <a className="text-gray-900 dark:text-white" href="#Contact">Contact</a>
            <a className="text-gray-900 dark:text-white" href="/resume.png">Resume</a>
            <TfiLightBulb
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-md px-2 ml-4 font-black text-gray-900 dark:text-white"
                />
          </nav>
      </div>

      <div className= "lg:hidden">
      <div class="grid grid-rows-3 grid-flow-col gap-7 text-left p-6">
          <a className="flex-shrink-0 pl-4 bg-clip-text bg-gradient-to-r from-red-900 to-slate-900 dark:to-slate-100  font-black text-transparent" href="#">Daniel Khan</a>
          <a className="flex-shrink-0 pl-4  text-gray-900 dark:text-white" href="#About">About</a>
          <a className="flex-shrink-0 pl-4  text-gray-900 dark:text-white" href="#Experience">Experience</a>
          <a className="flex-shrink-0 pl-4  text-gray-900 dark:text-white" href="#Projects">Projects</a>
          <a className="flex-shrink-0 pl-4  text-gray-900 dark:text-white" href="#Contact">Contact</a>
          <a className="flex-shrink-0 pl-4  text-gray-900 dark:text-white" href="/resume.png">Resume</a>
      </div>
      </div>

      </header>
      
      <body className="bg-stone-100 md:px-30 dark:bg-zinc-800 sm:px-20 lg:px-40">
        
          <div className="text-center py-10 max-w-screen-xl mx-auto">
          <h2 className="text-5xl pt-40 pb-10 text-red-600 dark:text-red-400 sm:text-6xl tracking-tight font-extrabold">
              Hi, I&apos;m Daniel
            </h2>
            <h3 className="text-5xl pb-40 text-red-600 dark:text-red-400 sm:text-6xl tracking-tight font-extrabold">
              Welcome to my website!
            </h3>
          </div>
          
          <section id="About">
          <h2 className="mb-4 text-4xl py-10 font-bold text-center text-gray-900 dark:text-white">A bit about me...</h2>
            
          <div className="grid gap-4 md:grid-cols-2 md:gap-4 lg:grid-cols-2 lg:gap-20 max-w-screen-xl mx-auto px-4 sm:px-6 lg:px-8">
              
            <p className="text-xl py-4 text-left text-gray-800 dark:text-gray-200 md:text-2xl lg:text-2xl">
            I am a highly motivated and ambitious individual with a passion for engineering and technology. I am always looking for new opportunities to learn and grow, and am committed to staying up-to-date with the latest developments in my field. I have a strong interest in problem-solving and innovation, and am dedicated to using my skills and knowledge to make a positive difference in the world. 
              </p>
            <a className="text-xl py-4 text-gray-800 dark:text-gray-200 md:text-2xl lg:text-2xl">
            <p className="pb-4 text-left">
              👨🏽‍💻 Product Engineer Intern @ Diversio
            </p>
            <p className="pb-4 text-left" >
              📚 Computer Engineering @ Ryerson University, 4th year
            </p>
            <p className="pb-4 text-left">
              🦾 Software Controls Member @ Ryerson Rams Robotics (R3)
            </p>
            </a>
            </div>
          </section>

 
        <section id="Experience">
          <div className="max-w-screen-xl mx-auto pb-10 px-4 sm:px-6 lg:px-8">
            
          <h2 className="mb-4 py-10 text-4xl  font-bold text-center text-gray-900 dark:text-white text-center">My Experience</h2>
          
          <div className="-my-8 divide-y-2 divide-gray-900 dark:divide-gray-100">
            <div className="py-8 flex flex-wrap md:flex-nowrap">
              <div className="md:w-64 md:mb-0 mb-6 flex-shrink-0 flex flex-col">
                <span className="font-normal text-gray-900 dark:text-white">Diversio</span>
                <span className="mt-1 text-gray-400 dark:text-gray-500 text-sm">May 2022 - December 2022</span>
              </div>
              <div className="md:flex-grow">
                <h2 className="text-2xl font-semibold text-gray-900 dark:text-white title-font mb-2">Product Engineering Intern</h2>
                <p className="mb-4 text-base font-normal text-gray-500 dark:text-gray-400">Creating Diverse and Inclusive workplaces using Python (Django) & React</p>
                <a href="https://diversio.com/diversio-insights/"><button type="button" className="bg-red-100 text-red-800 text-sm font-medium mr-2 px-2.5 py-0.5 rounded dark:bg-red-200 dark:text-red-800 hover:scale-105">Diversio Insights</button></a>
              </div>
            </div>
            
            <div className="py-8 flex flex-wrap md:flex-nowrap">
              <div className="md:w-64 md:mb-0 mb-6 flex-shrink-0 flex flex-col">
                <span className="font-normal text-gray-900 dark:text-white">Loblaw Companies Limited</span>
                <span className="mt-1 text-gray-400 dark:text-gray-500 text-sm">May 2021 - December 2021</span>
              </div>
              <div className="md:flex-grow">
                <h2 className="text-2xl font-semibold text-gray-900 dark:text-white title-font mb-2">Automation Developer Intern</h2>
                <p className="mb-4 text-base font-normal text-gray-500 dark:text-gray-400">Attended and provided updates in daily scrum meetings, specifically on a Power Automate flow which created and logged COVID-19 store operating hours for 1300+ Loblaw and Shoppers Drug Mart pharmacy locations, decreasing manual processes and increasing efficiency by 98%</p>
                <p className="mb-4 text-base font-normal text-gray-500 dark:text-gray-400">Developed a Python cript that performed hourly checks on file system’s (AIX) storage limits and reported results back to the system administrator via email, creating ServiceNow tickets for escalation when necessary to ensure the system did not exceed the server threshold</p>
                <a href="https://www.federalrapidscreening.morewaystobenefit.ca/"><button type="button" className="bg-red-100 text-red-800 text-sm font-medium mr-2 px-2.5 py-0.5 rounded dark:bg-red-200 dark:text-red-800  hover:scale-105">Rapid Screening Program</button></a>
              </div>
            </div>
            <div className="py-8 flex flex-wrap md:flex-nowrap">
              <div className="md:w-64 md:mb-0 mb-6 flex-shrink-0 flex flex-col">
                <span className="font-normal text-gray-900 dark:text-white">Ryerson Rams Robotics (R3)</span>
                <span className="mt-1 text-gray-400 dark:text-gray-500 text-sm">May 2022 - December 2022</span>
              </div>
              <div className="md:flex-grow">
                <h2 className="text-2xl font-semibold text-gray-900 dark:text-white title-font mb-2">Software Controls Developer</h2>
                <p className="mb-4 text-base font-normal text-gray-500 dark:text-gray-400">Designed and programmed a hockey goalkeeping robot for TSN which can be used wirelessly (through wifi connection) to accurately and easily control the arms of a goalkeeper</p>
                <p className="mb-4 text-base font-normal text-gray-500 dark:text-gray-400">Responsible for programming a microcontroller (ESP8266) along with a series of motors and actuators to wirelessly control a robot over a Socket Server with TCP and HTTP communication</p>
                <a href="https://teamr3.ca/"><button  type="button" className="bg-red-100 text-red-800 text-sm font-medium mr-2 px-2.5 py-0.5 rounded dark:bg-red-200 dark:text-red-800  hover:scale-105">R3 Site</button></a>
              </div>
            </div>

            <div className="py-8 flex flex-wrap md:flex-nowrap">
              <div className="md:w-64 md:mb-0 mb-6 flex-shrink-0 flex flex-col">
                <span className="font-normal text-gray-900 dark:text-white">Freelance</span>
                <span className="mt-1 text-gray-400 dark:text-gray-500 text-sm">May 2022 - December 2022</span>
              </div>
              <div className="md:flex-grow">
                <h2 className="text-2xl font-semibold text-gray-900 dark:text-white title-font mb-2">Software Developer</h2>
                <p className="mb-4 text-base font-normal text-gray-500 dark:text-gray-400">Created Python Scripts using social media API’s in order to handle social media account activity such as posting to pages and viewing analytics</p>
                <p className="mb-4 text-base font-normal text-gray-500 dark:text-gray-400">Automated social media posting, decreasing overall manual time spent by 90% (from 1 hour to 5 minutes) and successfully gaining 100k interactions per month</p>
              </div>
            </div>        
          </div>
          </div>
        </section> 





        <section className="text-white" id="Projects">
          
          <div className="mx-auto max-w-screen-xl px-4 py-16 sm:px-6 lg:px-8">

            <div className="mx-auto max-w-lg text-center">
              <h2 className="text-3xl font-bold sm:text-4xl text-gray-800 dark:text-gray-200">Some of my Projects</h2>
              <p className="mt-4 text-center text-gray-800 dark:text-gray-200">
                Here are some of the projects I have worked on!
              </p>
            
            </div>

              <div className="py-6 grid gap-8 grid-cols-1 md:grid-cols-2 lg:grid-cols-3">
                <a className="relative p-px rounded border border-gray-200 dark:border-gray-700 bg-day dark:bg-night bg-opacity-50 dark:bg-opacity-50 flex flex-wrap transform transition duration-500 cursor-pointer group hover:scale-105" href="/https://github.com/d27khan">
                  <div className="absolute bottom-0 left-0 w-full h-1 duration-300 origin-left transform scale-x-0 bg-accent group-hover:scale-x-100"></div>
                  <div className="absolute bottom-0 left-0 w-1 h-full duration-300 origin-bottom transform scale-y-0 bg-accent group-hover:scale-y-100"></div>
                  <div className="absolute top-0 left-0 w-full h-1 duration-300 origin-right transform scale-x-0 bg-accent group-hover:scale-x-100"></div>
                  <div className="absolute bottom-0 right-0 w-1 h-full duration-300 origin-top transform scale-y-0 bg-accent group-hover:scale-y-100"></div>
                  <div className="relative p-4 space-y-2 bg-day dark:bg-night">
                    <h2 className="mt-2 mb-2 w-11/12 md:text-xl font-bold inline-block">🧴DermaCare</h2>
                    <a href="https://github.com/d27khan"><RiGithubLine  className="cursor-pointer inset-y-0 right-0 inline-block"/></a>
                    <span className="w-full inline-flex gap-2 items-start">
                      <span className="inline-block py-1 px-2 rounded border border-gray-700 text-xs font-medium">Python</span>
                      <span className="inline-block py-1 px-2 rounded border border-gray-700 text-xs font-medium">Google Cloud</span>
                    </span>
                    <p className="text-sm text-gray-600 dark:text-gray-300 tracking-wider">A Web Application that analyzes your skin using machine learning</p>
                  </div>
                </a>
                <a className="relative p-px rounded border border-gray-200 dark:border-gray-700 bg-day dark:bg-night bg-opacity-50 dark:bg-opacity-50 flex flex-wrap transform transition duration-500 cursor-pointer group hover:scale-105" href="https://github.com/d27khan">
                  <div className="absolute bottom-0 left-0 w-full h-1 duration-300 origin-left transform scale-x-0 bg-accent group-hover:scale-x-100"></div>
                  <div className="absolute bottom-0 left-0 w-1 h-full duration-300 origin-bottom transform scale-y-0 bg-accent group-hover:scale-y-100"></div>
                  <div className="absolute top-0 left-0 w-full h-1 duration-300 origin-right transform scale-x-0 bg-accent group-hover:scale-x-100"></div>
                  <div className="absolute bottom-0 right-0 w-1 h-full duration-300 origin-top transform scale-y-0 bg-accent group-hover:scale-y-100"></div>
                  <div className="relative p-4 space-y-2  dark:bg-night">
                    <a href=""><MdOutlineFeaturedPlayList  className="align-text-top inline-block pr-1"/></a>
                    <h2 className="mt-2 w-10/12 mb-2 md:text-xl font-bold inline-block">LSPro</h2>
                    <a href="https://github.com/d27khan"><RiGithubLine  className="cursor-pointer inset-y-0 right-0 inline-block"/></a>
                    <span className="w-full inline-flex gap-2 items-start">
                      <span className="inline-block py-1 px-2 rounded border border-gray-700 text-xs font-medium">C</span>
                    </span>
                    <p className="text-sm text-gray-600 dark:text-gray-300 tracking-wider">A Command line tool aiming to make the list command interactive</p>
                  </div>
                </a>
                <a className="relative p-px rounded border border-gray-200 dark:border-gray-700 bg-day dark:bg-night bg-opacity-50 dark:bg-opacity-50 flex flex-wrap transform transition duration-500 cursor-pointer group hover:scale-105" href="https://github.com/d27khan">
                  <div className="absolute bottom-0 left-0 w-full h-1 duration-300 origin-left transform scale-x-0 bg-accent group-hover:scale-x-100"></div>
                  <div className="absolute bottom-0 left-0 w-1 h-full duration-300 origin-bottom transform scale-y-0 bg-accent group-hover:scale-y-100"></div>
                  <div className="absolute top-0 left-0 w-full h-1 duration-300 origin-right transform scale-x-0 bg-accent group-hover:scale-x-100"></div>
                  <div className="absolute bottom-0 right-0 w-1 h-full duration-300 origin-top transform scale-y-0 bg-accent group-hover:scale-y-100"></div>
                  <div className="relative p-4 space-y-2 bg-day dark:bg-night">
                    <a href=""><ImAmazon  className="align-text-top inline-block pr-1"/></a>
                    <h2 className="mt-2 w-10/12 mb-2 md:text-xl font-bold inline-block">Amazon Price Tracker</h2>
                    <a href="https://github.com/d27khan"><RiGithubLine  className="cursor-pointer inset-y-0 right-0 inline-block"/></a>
                    <span className="w-full inline-flex justify-between items-center">
                      <span className="inline-block py-1 px-2 rounded border border-gray-700 text-xs font-medium">Python</span>
                    </span>
                    <p className="text-sm text-gray-600 dark:text-gray-300 tracking-wider">Keep track of prices on your favourite Amazon items with this script!</p>
                  </div>
                </a>
                <a className="relative p-px rounded border border-gray-200 dark:border-gray-700 bg-day dark:bg-night bg-opacity-50 dark:bg-opacity-50 flex flex-wrap transform transition duration-500 cursor-pointer group hover:scale-105" href="https://github.com/d27khan">
                  <div className="absolute bottom-0 left-0 w-full h-1 duration-300 origin-left transform scale-x-0 bg-accent group-hover:scale-x-100"></div>
                  <div className="absolute bottom-0 left-0 w-1 h-full duration-300 origin-bottom transform scale-y-0 bg-accent group-hover:scale-y-100"></div>
                  <div className="absolute top-0 left-0 w-full h-1 duration-300 origin-right transform scale-x-0 bg-accent group-hover:scale-x-100"></div>
                  <div className="absolute bottom-0 right-0 w-1 h-full duration-300 origin-top transform scale-y-0 bg-accent group-hover:scale-y-100"></div>
                  <div className="relative p-4 space-y-2 bg-day dark:bg-night">
                    <h2 className="mt-2 mb-2 w-11/12 md:text-xl inline-block font-bold">📚 Book Store App</h2>
                    <a href="https://github.com/d27khan"><RiGithubLine  className="cursor-pointer inset-y-0 right-0 inline-block"/></a>
                    <span className="w-full inline-flex justify-between items-center">
                      <span className="inline-block py-1 px-2 rounded border border-gray-700 text-xs font-medium">Java</span>
                    </span>
                    <p className="text-sm text-gray-600 dark:text-gray-300 tracking-wider">A stand alone library management desktop applicaiton</p>
                  </div>
                </a>

                
              </div>

          </div>
        </section>


        <section className="text-white" id="CurrentProjects">
          
          <div className="mx-auto max-w-screen-xl px-4 py-16 sm:px-6 lg:px-8">
          <h2 className="text-3xl font-bold sm:text-4xl text-center text-gray-800 dark:text-gray-200">What I&apos;m up to</h2>
            
            <div className="mx-auto max-w-lg py-4">
              
              
              <div className="bg-yellow-100 w-full rounded border-l-4 py-2 border-yellow-500">
                <div className="flex space-x-3">
                <a href=""><VscWarning  className="align-text-bottom text-bold text-lg text-yellow-500 pl-1 right-0 inline-block"/></a>
                
                  <div className="flex-1 leading-tight text-md  text-gray-900">I will be updating this section soon with my current projects</div>
                </div>
              </div>
              <p className="mt-4 text-center inline-block text-gray-800 dark:text-gray-200 ">Checkout my github</p>
              <a href="https://github.com/d27khan"><VscGithubInverted  className="cursor-pointer text-red-600 dark:text-red-400 align-text-bottom pl-1 right-0 inline-block"/></a>
            </div>
          </div>
        </section>


        <section className="py-10" id="Contact">
          <div>
            <div className="py-8 lg:py-16 px-6 mx-auto max-w-screen-md sm:px-6 lg:px-8">
              <h2 className="mb-4 text-4xl tracking-tight font-extrabold text-center text-gray-900 dark:text-white">Lets get in Touch!</h2>
              <p className="mb-8 lg:mb-16 font-light text-center text-gray-500 dark:text-gray-400 sm:text-xl"></p>
              <form action="#" className="space-y-8">
                  <div>
                      <label htmlFor="email" className="block mb-2 text-md font-medium text-gray-900 dark:text-gray-300">Your email</label>
                      <input type="email" id="email" className="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500 dark:shadow-sm-light" placeholder="name@email.com" required></input>
                  </div>
                  <div>
                      <label htmlFor="subject" className="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300">Subject</label>
                      <input type="text" id="subject" className="block p-3 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 shadow-sm focus:ring-primary-500 focus:border-primary-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500 dark:shadow-sm-light" placeholder="Let me know what I can do!" required></input>
                  </div>
                  <div className="sm:col-span-2">
                      <label htmlFor="message" className="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-400">Your message</label>
                      <textarea id="message" rows="6" className="block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg shadow-sm border border-gray-300 focus:ring-primary-500 focus:border-primary-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500" placeholder="Leave a comment..."></textarea>
                  </div>
                  <button type="submit" className="py-3 px-5 text-sm font-medium text-center text-white rounded-lg bg-primary-700 sm:w-fit hover:bg-primary-800 focus:ring-4 focus:outline-none focus:ring-primary-300 dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800">Send message</button>
              </form>
            </div>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap max-w-screen-xl mx-auto">

          <a href="#"><AiOutlineToTop  className="text-4xl cursor-pointer font-black text-gray-900 dark:text-white justify-end"/></a>
          </div>
        </section>
        <script src="../node_modules/flowbite/dist/flowbite.min.js"></script>
      </body>
      <footer className=" bg-red pb-10 bg-stone-100 px-10 dark:bg-zinc-800 sm:px-20 lg:px-40">
          <div className="max-w-screen-xl mx-auto">
            <p className="text-center font-light py-2 leading-8 justify-center text-gray-800 dark:text-gray-200">
              Designed & built by Daniel Khan using tailwindcss & next.js
            </p>
            <div className="text-xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a href="https://github.com/d27khan"><VscGithubInverted  className=" cursor-pointer"/></a>
              <a href="https://linkedin.com/in/danielkhan-"><SiLinkedin className=" cursor-pointer" /></a>
              <a href="https://www.google.com/search?q=toronto"><BsFillPinMapFill  className=" cursor-pointer"/></a>
              <a href="mailto:daniel.khan@ryerson.ca"><GrMail className=" cursor-pointer" /></a>
              <a href="https://www.torontomu.ca/programs/undergraduate/computer-engineering/"><IoMdSchool className=" cursor-pointer" /></a>
            </div>
          </div>
          </footer>
        </div>
  );
}